# Generated by Selenium IDE
import pytest
import time
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
import datetime

class TestPrivacyPolicy():
    def setup_method(self, method):
        # Use headless Chrome for CI
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Chrome(options=chrome_options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_privacyPolicy(self):
        # Navigate to the website
        self.driver.get("https://smoothmaths.co.uk/")
        self.driver.set_window_size(1296, 696)
        
        # Scroll down and click the Privacy Policy link
        self.driver.execute_script("window.scrollTo(0, 1055.3333740234375)")
        self.driver.execute_script("window.scrollTo(0, 3176)")
        self.driver.find_element(By.LINK_TEXT, "Privacy Policy").click()

        # Verify if the correct URL is loaded
        time.sleep(3)  # Wait for the page to load
        current_url = self.driver.current_url
        expected_url = "https://smoothmaths.co.uk/privacy-policy/"
        
        # Save screenshot with timestamp
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        screenshot_path = f"screenshots/privacy_policy_{timestamp}.png"
        os.makedirs(os.path.dirname(screenshot_path), exist_ok=True)
        self.driver.save_screenshot(screenshot_path)

        # Check if the current URL is the expected URL
        try:
            assert current_url == expected_url, f"Expected URL: {expected_url}, but got {current_url}"
            print(f"Test passed. Navigated to the correct URL: {current_url}")
        except AssertionError as e:
            print(f"Test failed: {e}")
            raise e

